port 0
tls-port 6379

# 证书与私钥
tls-cert-file /etc/valkey/tls/valkey-node.crt
tls-key-file  /etc/valkey/tls/valkey-node.key

# 单一套体系下，不管是验客户端还是验对端节点，都只用这一个根 CA
tls-ca-cert-file /etc/valkey/tls/valkey-root.crt

# 开启全通道双向认证
tls-auth-clients yes
tls-cluster yes
tls-replication yes

# 集群基础配置
cluster-enabled yes
cluster-config-file /data/nodes.conf
cluster-node-timeout 5000


# 开启集群主机名宣告功能
cluster-preferred-endpoint-type hostname

# 指定当前节点的主机名（每个节点的 conf 文件里这行要写各自对应的域名）
cluster-announce-hostname valkey-cluster-conoha-ndhealth.wator.xyz

# 宣告端口（保持与你的 tls-port 一致）
cluster-announce-tls-port 6379

# 优化 TLS 1.3 密码套件
tls-protocols "TLSv1.3"
tls-ciphersuites TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256
