services:
#  nginx-openresty:
#    image: openresty/openresty:alpine
#    volumes:
#      - ./Nginx_Gate/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
#      - ./Nginx_Gate/proxy.lua:/usr/local/openresty/nginx/conf/proxy.lua:ro
#      - ./Nginx_Gate/ssl_certificate.lua:/usr/local/openresty/nginx/conf/ssl_certificate.lua:ro
#      - /opt/otmc-deploy/otmc.secret/broker/server_cert:/usr/local/openresty/nginx/conf/server_cert:ro
#      - /opt/otmc-deploy/otmc.secret/broker/client_cert:/usr/local/openresty/nginx/conf/client_cert:ro
#      # 挂载共享卷，与 broker 共用
#      - mqtt_socket:/var/run/mqtt
#    network_mode : "host"
#    #ports:
#      # nginx 监听端口，客户端连接此处
#      #- "8443:8443"
#    depends_on:
#      - mqtt-broker

  haproxy:
    image: openresty/openresty:alpine
    volumes:
      - ./HAProxy_Gate/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./HAProxy_Gate/lua:/usr/local/etc/haproxy/lua:ro
      - /opt/otmc-deploy/otmc.secret/broker/server_cert:/usr/local/openresty/nginx/conf/server_cert:ro
      - /opt/otmc-deploy/otmc.secret/broker/client_cert:/usr/local/openresty/nginx/conf/client_cert:ro
      # 挂载共享卷，与 broker 共用
      - mqtt_socket:/var/run/mqtt
    network_mode : "host"
    #ports:
      # nginx 监听端口，客户端连接此处
      #- "8443:8443"
    depends_on:
      - mqtt-broker

  valkey:
    image: valkey/valkey:9.1
    volumes:
      - ./valkey/valkey.conf:/etc/valkey/valkey.conf
      - ./valkey_data:/data
    ports:
      # valkey 监听端口，客户端连接此处
      - "6379:6379"
    command: valkey -c /etc/valkey/valkey.conf

  mqtt-broker:
    build:
      context: ./
      dockerfile: ./CXX_Broker/Dockerfile.runtime
    volumes:
      # 同一共享卷，broker 在此创建 socket 文件
      - mqtt_socket:/var/run/mqtt              
    environment:
      # 假设您的 broker 通过环境变量指定路径
      - SOCKET_PATH=/var/run/mqtt/broker.external.sock  
volumes:
  # 定义共享卷，用于传递 Unix socket 文件
  mqtt_socket:   
  valkey_data: