worker_processes  1;

events {
    worker_connections  1024;
}

# 注意：这是 stream 块，与 http 块平级
stream {
    log_format mqtt_proxy '$remote_addr [$time_local] $protocol '
                          '$status $bytes_sent $bytes_received '
                          '$session_time "$upstream_addr"';
    access_log /dev/stdout mqtt_proxy;
    error_log  /dev/stderr debug;


    upstream mqtt_backend {
        # 后端 MQTT Broker 地址
        server unix:/var/run/otmc/mqtt.sock;  
    }

    server {
        # 监听 18883 端口并开启 SSL
        listen 18883 ssl;
        listen [::]:18883 ssl;

        # --- 服务端证书配置 ---
        ssl_certificate      /usr/local/etc/certs/internal_cert/internal-server.crt;
        ssl_certificate_key  /usr/local/etc/certs/internal_cert/internal-server.key;

        # --- mTLS 客户端验证配置 ---
        ssl_client_certificate /usr/local/etc/certs/internal_cert/internal-root.crt;
        ssl_verify_client      on; # 强制验证客户端证书
        ssl_verify_depth       2; # 验证深度，允许客户端证书链长度为 2
        
        proxy_pass mqtt_backend;
    }
}
