worker_processes  1;

events {
    worker_connections  1024;
}

# 注意：这是 stream 块，与 http 块平级
stream {
    log_format mqtt_proxy '$remote_addr [$time_local] $protocol '
                          '$status $bytes_sent $bytes_received '
                          '$session_time "$upstream_addr"';
    access_log /dev/stdout mqtt_proxy;
    error_log  /dev/stderr debug;
    # 动态加载 Lua 模块路径（如果需要的话）
    lua_package_path '/usr/local/openresty/nginx/conf/?.lua;;';

    server {
        # 监听 8443 端口并开启 SSL
        listen 8443 ssl;

        # --- 服务端证书配置 ---
        ssl_certificate      /usr/local/openresty/nginx/conf/server_cert/fullchain.crt;
        ssl_certificate_key  /usr/local/openresty/nginx/conf/server_cert/server-leaf.key;

        # --- mTLS 客户端验证配置 ---
        ssl_client_certificate /usr/local/openresty/nginx/conf/client_cert/ca.crt;
        ssl_verify_client      on; # 强制验证客户端证书
        ssl_verify_depth       5;

        # 在内容阶段调用外部 Lua 文件进行 TCP 转发
        content_by_lua_file /usr/local/openresty/nginx/conf/proxy.lua;
    }
}
