worker_processes  1;

events {
    worker_connections  1024;
}

# 注意：这是 stream 块，与 http 块平级
stream {
    log_format mqtt_proxy '$remote_addr [$time_local] $protocol '
                          '$status $bytes_sent $bytes_received '
                          '$session_time "$upstream_addr"';
    access_log /dev/stdout mqtt_proxy;
    error_log  /dev/stderr debug;
    # 动态加载 Lua 模块路径（如果需要的话）
    lua_package_path '/usr/local/openresty/nginx/conf/?.lua;;';


    upstream mqtt_backend {
        # 后端 MQTT Broker 地址（这里以本地 Mosquitto 为例）
        server 127.0.0.1:21883;
    }

    server {
        # 监听 8443 端口并开启 SSL
        listen 8443 ssl;
        listen [::]:8443 ssl;

        # --- 服务端证书配置 ---
        ssl_certificate      /usr/local/openresty/nginx/conf/server_cert/fullchain.crt;
        ssl_certificate_key  /usr/local/openresty/nginx/conf/server_cert/server-leaf.key;

        # --- mTLS 客户端验证配置 ---
        ssl_client_certificate /usr/local/openresty/nginx/conf/client_cert/ca.crt;
        ssl_verify_client      on; # 强制验证客户端证书
        ssl_verify_depth       6;

        ssl_certificate_by_lua_block {
            ngx.log(ngx.INFO, "ngx.var.ssl_client_verify: ", ngx.var.ssl_client_verify)            
            ngx.log(ngx.INFO, "ngx.var.ssl_client_escaped_cert: ", ngx.var.ssl_client_escaped_cert)
            local ssl = require("ngx.ssl")
            local chain, err = ssl.raw_client_cert_chain()
            if chain then
                for i, cert in ipairs(chain) do
                    ngx.log(ngx.INFO, "Certificate ", i, ":\n", cert)
                end
            else
                ngx.log(ngx.ERR, "Failed to get chain: ", err)
            end
        }
        preread_by_lua_block {
            ngx.log(ngx.INFO, "ngx.var.ssl_client_verify: ", ngx.var.ssl_client_verify)            
            ngx.log(ngx.INFO, "ngx.var.ssl_client_escaped_cert: ", ngx.var.ssl_client_escaped_cert)
            ngx.log(ngx.INFO, "ngx.var.ssl_client_raw_cert: ", ngx.var.ssl_client_raw_cert)
            local raw_chain = ngx.var.ssl_client_raw_cert
            if raw_chain then
                local cert_count = 0
                for cert in raw_chain:gmatch("-----BEGIN CERTIFICATE-----\n?.-\n?-----END CERTIFICATE-----\n?") do
                    cert_count = cert_count + 1
                    ngx.log(ngx.INFO, "Certificate ", cert_count, ":\n", cert)
                end
                ngx.log(ngx.INFO, "Total certificates in chain: ", cert_count)
            end

        }
        proxy_pass mqtt_backend;
    }
}
