FROM ubuntu:26.04
RUN apt-get update && apt-get install -y \
        build-essential \
        cmake \
        libssl-dev \
        libz-dev \
        libuuid-dev \
        libzmq3-dev \
        libboost-dev \
        libboost-program-options-dev \
        libboost-system-dev \
        libboost-thread-dev \
        libboost-chrono-dev
